#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, apples, oranges):
        #apples that fell on sams house 
        apple_sum = 0;
        for apple in apples:
            appledistance  = apple + a;
            if appledistance <= t and appledistance >= s:
                apple_sum = apple_sum + 1;
            
        #oranges that fell on sams house 
        orange_sum = 0;
        for orange in oranges:
            orangedistance  = orange + b;
            
            if orangedistance <= t and orangedistance >= s:
                orange_sum = orange_sum + 1;      

        print(apple_sum)
        print(orange_sum)
   


if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
