#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the birthdayCakeCandles function below.

def birthdayCakeCandles(ar):
    tallest = 0;
    count = 0
    for n in ar:
        if n > tallest:
            tallest  = n
    

    for n in ar:
        if n == tallest:
            count = count + 1;
    
    return count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(ar)

    fptr.write(str(result) + '\n')

    fptr.close()
