#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the extraLongFactorials function below.
def extraLongFactorials(n):
            i = 1;
            sum = 1;
            while i <= n:

                sum = sum * i;
                i = i+1
            
            print(sum)



if __name__ == '__main__':
    n = int(input())

    extraLongFactorials(n)
